mod AST;
mod lexer;
mod parser;
mod symbol_table;
mod tokens;
mod transpile_c;

use crate::lexer::Lexer;
use crate::parser::Parser;
use crate::transpile_c::transpile_to_c;
use std::{env, fs, io, path::PathBuf, process::Command};

// ============================================================================
// DEVELOPMENT NOTE:
// Initial logic for this system was drafted using AI pseudocode.
// The entire codebase has since been manually rewritten, refactored, and
// engineered from scratch. Future development is entirely human-written.
// ============================================================================
fn main() -> io::Result<()> {
    println!("Welcome to Obsidian compiler/transpiler");

    // Check for gcc
    if !gcc_exists() {
        eprintln!("Error: gcc was not found in PATH.");
        std::process::exit(1);
    }

    // Get source file from CLI args
    let args: Vec<String> = env::args().collect();

    if args.len() != 2 {
        eprintln!("Usage: obsidian <absolute-path-to-file.obs>");
        std::process::exit(1);
    }

    let source_path = PathBuf::from(&args[1]);

    // Require absolute path
    if !source_path.is_absolute() {
        eprintln!("Error: please provide an absolute path.");
        std::process::exit(1);
    }

    let src = fs::read_to_string(&source_path)?;

    let mut lexer = Lexer::new(src);

    println!("Starting lexer");
    lexer.tokenize();

    let mut parser = Parser::new(lexer.tokens_out);
    let parser_out = parser.parse();

    let c_out = transpile_to_c(parser_out);

    fs::write("output.c", c_out)?;

    println!("========== program output ==========\n");

    compile_and_run()?;

    Ok(())
}

fn gcc_exists() -> bool {
    Command::new("gcc").arg("--version").output().is_ok()
}

//THIS CODE WAS GENERATED BY CHAT GPT!

fn compile_and_run() -> io::Result<()> {
    // 1. Compile C code
    let compile_status = Command::new("gcc")
        .args(["output.c", "-o", "output"])
        .status()?;

    if !compile_status.success() {
        panic!("GCC compilation failed");
    }

    // 2. Run program
    let run_status = Command::new("./output").status()?;

    if !run_status.success() {
        panic!("Program execution failed");
    }

    Ok(())
}
